function(libpic_add_test test_name source)
    add_executable(${test_name} ${source})
    target_link_libraries(${test_name} PRIVATE libpic)
    target_include_directories(${test_name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
    add_test(NAME ${test_name} COMMAND ${test_name})
endfunction()

libpic_add_test(test_input test_input.c)
libpic_add_test(test_input_group test_input_group.c)
libpic_add_test(test_input_pattern test_input_pattern.c)
libpic_add_test(test_output test_output.c)
libpic_add_test(test_output_group test_output_group.c)
libpic_add_test(test_timer test_timer.c)
libpic_add_test(test_trigger test_trigger.c)
